### ISSUE TITLE
ITC integration

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/basic-case#7]
Here are some thoughts on getting ITC integrated. I think we need to do it sooner rather than later because all of our automation will depend on ITC calculations and we need to be sure

- we're collecting enough information;
- we're choosing or computing reasonable defaults for information we don't collect; and
- we're capable of performing the necessary computations. 

Lots of things aren't supported yet in ITC. Two that I ran into just today for the basic case are

- nod and shuffle for Hamamatsu detectors; and 
- total exposures to meet S/N requirements.

We need to discover these deficiencies so we can get them fixed, otherwise our ability to automate stuff will be limited.
____

Integrating ITC into basic-case (and eventually OCS3) isn't straightforward.

- Ultimately it's just a function (defined [here](https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.itc.shared/src/main/scala/edu/gemini/itc/shared/ItcService.scala#L183-L189)) but its parameter and return types are both complex and pull in big hunks of OCS and likely some scalaz types like `\/`.
- The ITC pages on the Gemini website talk to a servlet that takes a bunch of parameters and spits out results in text format, so it's easy to call but the results are very hard to interpret. We *could* scrape the output but this seems like a grim and error-prone exercise.
- The OT talks to the ODB-integrated ITC via TRPC, so it acts like it has a local instance of `ItcService`. Implementing TRPC in our new codebase wouldn't be hard, but porting the input and output types over to 2.12 in a serialization-compatible way (recall we're just serializing blobs) is at very least hard, and maybe impossible.

I don't think it makes sense to migrate the ITC to cats/2.12/OCS3 until old OCS is more or less shut down. The ITC is under constant maintenance and will require a lot of work to satisfy the requirements we're looking at for OCS3. So I think it's best to leave it as-is.

So I think maybe we need to add a new service to OCS that exposes a web API for the ITC, possibly even GraphQL. Another option would be to write an independent proxy service in 2.11 that speaks TRPC to the ODB and exposes a web API for basic-case and OC3 to use.

**Comment by cquiroz** [comment]
considering how key the ITC will be in the ocs3 perhaps it is worth to rewrite some parts at least. We should build a deep understanding of it

**Comment by tpolecat** [comment]
Yeah I agree we need to rewrite it, and I guess one way to do it would be to GC stuff over on demand and clean it up as we go. What I worry about is the constant tinkering (every release has ITC changes) that would need to be kept in sync between the old and new versions. There's also the question of whether we need to preserve the old HTML user interface … I kind of expect we do.

**Comment by cquiroz** [comment]
I agree keeping those changes would be a pain, perhaps ocs2 should use this new itc instead.
The HTML part is really clunky to maintain

**Comment by tpolecat** [comment]
The three ITC bundles contain 9504 lines of Java and 2660 lines of Scala so it's not a *huge* amount of code but it's not trivial either. Of these lines only 960 are for tests so I suspect test coverage is pretty bad, which will make porting this code kind of treacherous.

**Comment by tpolecat** [comment]
I'm going to mark this one as resolved.
